baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "HackerZ - Test Hugo"
theme = "hyde"

[params]
    description = "这里是HackerZ的个人博客"
    themeColor = "theme-base-08"  # for hyde theme
