baseurl = "http://hackez.github.io//"
#baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "HackerZ - Blog"
theme = "hyde"

[Author]
    Name = "HackerZ"

[params]
    description = "Welcome to my personal Blog"
    themeColor = "theme-base-08"  # for hyde theme
    Imglogo = "author-head.png"

[Menu]
    [[Menu.main]]
        Name = "Book List"
        URL  = "/booklist"
        Weight = 1
